Repository elastic/apm-agent-python, pull requests merged in 2019-07, with the labels that each got.

#508 ci: fix wrapping-up
  .ci/downstreamTests.groovy
Labels: automation

#509 ci: ignore SCM triggers on downstream job
  .ci/jobs/apm-agent-python-downstream.yml
Labels: automation

#512 ci: fix missing imports
  .ci/Jenkinsfile
Labels: automation

#513 ci: add missing xkey for exclusions
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
Labels: [zube]: In Review, automation

#514 fix: set correct target branch
  .ci/Jenkinsfile
Labels: automation

#515 ci: remove warmError
  .ci/Jenkinsfile
Labels: [zube]: In Review, automation, ci

#516 fix: remove dead code with an undefined variable
  .ci/Jenkinsfile
Labels: [zube]: In Review, automation, ci

#524 fix: user error step, allow empty junit results
  .ci/downstreamTests.groovy
  Jenkinsfile
Labels: automation, bug, ci

#525 fix: user error step, allow empty junit results
  Jenkinsfile
Labels: automation, bug, ci

#532 ci: remove the documentation stage
  .ci/Jenkinsfile
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#534 ci: enable pre-commit stage within the Jenkins pipeline
  .ci/Jenkinsfile
  .pre-commit-config.yaml
  Jenkinsfile
  docs/run-tests-locally.asciidoc
Labels: automation, ci, enhancement

#536 ci: use preCommit step
  .ci/Jenkinsfile
  Jenkinsfile
Labels: [zube]: In Review, automation, ci
