Repository elastic/apm-agent-python, pull requests merged in 2019-09, with the labels that each got.

#582 ci(jenkins): disable shallow clone
  .ci/downstreamTests.groovy
Labels: automation, ci

#583 ci(jenkins): Set GitHub notification context to apm-ci
  .ci/jobs/apm-agent-python-downstream.yml
  .ci/jobs/apm-agent-python-mbp.yml
  .ci/jobs/apm-agent-python-mbp0.yml
Labels: [zube]: In Review, automation, ci

#588 ci(jenkins): change the github comment for the linters
  .ci/linting.groovy
Labels: automation, ci

#593 [docs] Add ECS versioning
  docs/index.asciidoc
Labels: docs
