Repository elastic/apm-agent-python, pull requests merged in 2019-11, with the labels that each got.

#609 ci(jenkins): send email before release approval
  .ci/Jenkinsfile
  Jenkinsfile
Labels: automation

#634 ci(jenkins): downstream@master log rotation didn't keep too many builds in the history
  .ci/downstreamTests.groovy
Labels: automation, ci

#617 [docs] Documentation restructure
  CHANGELOG.asciidoc
  docs/advanced-topics.asciidoc
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/django.asciidoc
  docs/flask.asciidoc
  docs/getting-started.asciidoc
  docs/how-the-agent-works.asciidoc
  docs/index.asciidoc
  docs/logging.asciidoc
  docs/metrics.asciidoc
  docs/opentracing.asciidoc
  docs/set-up.asciidoc
  docs/supported-technologies.asciidoc
  docs/tuning.asciidoc
Labels: docs

#619 [docs] Build release notes to documentation
  CHANGELOG.asciidoc
  CHANGELOG.md
  docs/release-notes.asciidoc
Labels: docs

#640 fix: remove downstream approach jobs
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  .ci/jobs/apm-agent-python-downstream.yml
  .ci/jobs/apm-agent-python-mbp0.yml
Labels: automation, ci

#641 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#643 Fixed spelling mistake in custom span example.
  docs/api.asciidoc
Labels: docs

#651 ci(jenkins): enable benchmark run
  .gitignore
  Jenkinsfile
  scripts/run-benchmarks.sh
Labels: automation, ci

#658 ci(jenkins): cancel previous running builds
  Jenkinsfile
Labels: automation, ci
