Repository elastic/apm-agent-python, pull requests merged in 2019-06, with the labels that each got.

#486 feat(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
Labels: [zube]: In Review, automation

#477 [APM-CI][All] Make the trigger by comment case-insensitive
  Jenkinsfile
Labels: automation

#492 [APM-CI] Fix lint issues with the check_paths_for_matches.py file
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#493 fix: add Elasticsearch URL
  Jenkinsfile
Labels: automation

#494 feat(jenkins): GH Checks for the PR
  Jenkinsfile
Labels: automation

#488 [docs][7.2] update config-environment
  docs/configuration.asciidoc
Labels: docs

#502 ci: fix JJBB job properties are duplicated
  .ci/jobs/elastic+apm-agent-python+master+periodic-full-matrix.yml
Labels: automation

#501 ci(jenkins): trigger async ITs and update github check for the pull request
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#487 ci(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
Labels: [zube]: In Review, automation

#505 ci: downstream job
  .ci/downstreamTests.groovy
  .ci/jobs/apm-agent-python-downstream.yml
Labels: automation

#507 ci: fix downstream job
  .ci/downstreamTests.groovy
Labels: automation

#506 ci(jenkins): notify first time contributor github check
  Jenkinsfile
Labels: automation, ci

#504 ci(jenkins): enable pull requests using the upstream repo
  Jenkinsfile
Labels: automation
