Repository elastic/apm-agent-python, pull requests merged in 2019-12, with the labels that each got.

#656 ci(jenkins): trigger opbeans release process
  Jenkinsfile
Labels: automation, ci

#670 [jjbb] enable the full nightly jobs as they were disable
  .ci/jobs/apm-agent-python-nightly-mbp.yml
  .ci/jobs/elastic+apm-agent-python+master+multijob+periodic-full-matrix-tests.yml
  .ci/jobs/elastic+apm-agent-python+master+periodic-full-matrix.yml
  .ci/nightly.groovy
Labels: automation, bug, ci

#672 [jjbb] 1w rather than 7d
  .ci/jobs/apm-agent-python-nightly-mbp.yml
Labels: automation, bug, ci

#676 [docs] add direct_html flag
  scripts/build_docs.sh
Labels: docs
