Repository elastic/apm-agent-python, pull requests merged in 2019-08, with the labels that each got.

#545 ci: fix tag pattern to be REGEX based and less restrictive
  .ci/Jenkinsfile
  Jenkinsfile
Labels: automation, bug, ci

#556 fix: it does not use the gitCheckout step anymore
  .ci/linting.groovy
Labels: automation, bug, ci

#552 docs: update branch for 4.x
  docs/index.asciidoc
Labels: docs

#557 ci(jenkins): delegate docker setup to the preCommit step
  .ci/Jenkinsfile
  .ci/linting.groovy
Labels: automation, ci

#558 ci(jenkins): delegate docker setup to the preCommit step
  Jenkinsfile
Labels: automation, ci

#559 Revert "ci(jenkins): delegate docker setup to the preCommit step"
  .ci/Jenkinsfile
  .ci/linting.groovy
  Jenkinsfile
Labels: automation, bug, ci

#560 chore: update build URL and build status icon
  README.rst
Labels: automation, ci, docs

#568 ci(jenkins): avoid using the any agent to skip running in the master-worker
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  .ci/linting.groovy
  Jenkinsfile
Labels: automation, ci, enhancement

#569 ci(jenkins): the environment GIT_BASE_COMMIT is not accessible
  .ci/Jenkinsfile
  Jenkinsfile
Labels: automation, bug, ci
