Repository elastic/apm-agent-python, pull requests merged in 2020-02, with the labels that each got.

#711 [docs] Fix link in changelog
  CHANGELOG.asciidoc
Labels: docs

#714 [docs] Update docs release process
  CONTRIBUTING.md
Labels: docs

#715 [docs] Add EOL table to documentation
  CHANGELOG.md
  CONTRIBUTING.md
  docs/upgrading.asciidoc
Labels: docs

#719 ci: grab Docker containers logs
  Jenkinsfile
  tests/scripts/docker/docker-get-logs.sh
  tests/scripts/docker/docker-summary.sh
  tests/scripts/docker/run_tests.sh
Labels: automation, ci

#721 ci: fix dir step
  Jenkinsfile
  tests/scripts/docker/run_tests.sh
Labels: automation, bug, ci

#729 ci(jenkins): use the cloud benchmark cluster
  Jenkinsfile
Labels: automation, bug, ci

#730 ci(jenkins): install python3 for the given VERSION
  scripts/install-python.ps1
Labels: automation, ci, enhancement

#736 ci(jenkins): send downstream build data to ES is not required anymore
  Jenkinsfile
Labels: automation, ci

#734 Disable codecov
  codecov.yml
Labels: ci

#728 ci(jenkins): run opbeans validation per PR
  Jenkinsfile
Labels: automation, ci, enhancement

#742 ci(jenkins): apm-its-downstream params has changed
  Jenkinsfile
Labels: automation
