Repository elastic/apm-agent-python, pull requests merged in 2020-03, with the labels that each got.

#735 [CI] Use cobertura for coverage reports [WIP]
  .gitignore
  Jenkinsfile
  Makefile
  setup.cfg
  tests/requirements/requirements-base.txt
  tests/scripts/docker/run_tests.sh
Labels: ci

#746 ci(jenkins): use CI Windows workers
  .appveyor.yml
  .ci/.jenkins_windows.yml
  Jenkinsfile
  scripts/install-python.ps1
  scripts/install-tools.bat
  scripts/run-tests.bat
  tests/scripts/download_gherkin_features.bat
  tests/scripts/download_json_schema.bat
Labels: automation, ci

#751 ci(jenkins): fix benchmark PATH variable
  Jenkinsfile
Labels: automation, bug, ci

#750 ci(jenkins): support 2.7 python in Windows
  .ci/.jenkins_windows.yml
  Jenkinsfile
  scripts/install-tools.bat
  scripts/run-tests.bat
  tests/appveyor/build.cmd
Labels: automation, ci

#760 chore: rename parent stage Release
  Jenkinsfile
Labels: automation, chore

#767 ci(jenkins): run full test matrix on a PR basis if comment
  .ci/jobs/apm-agent-python-nightly-mbp.yml
  Jenkinsfile
Labels: automation, ci

#776 docs: Add link to Agent/Server compatibility
  docs/getting-started.asciidoc
Labels: docs

#779 ci(jenkins): disable stages for only docs
  Jenkinsfile
Labels: automation

#782 chore: remove automation to pull gherkin specs
  .gitignore
  Makefile
  scripts/run-tests.bat
  tests/bdd/features/api_key.feature
  tests/scripts/download_gherkin_features.bat
  tests/scripts/download_gherkin_features.sh
  tests/scripts/run_tests.sh
Labels: automation
