Repository elastic/apm-agent-python, pull requests merged in 2020-06, with the labels that each got.

#852 ci: dockerLogs step
  Jenkinsfile
  tests/scripts/docker/docker-get-logs.sh
  tests/scripts/docker/run_tests.sh
Labels: automation, ci

#851 ci: run benchmark on a PR basis if comment
  Jenkinsfile
Labels: automation, ci

#863 fix: check that docker is installed
  .ci/packer_cache.sh
Labels: [zube]: In Review, automation, bug, ci

#865 [jjbb]: folder description is required
  .ci/jobs/apm-agent-python.yml
Labels: automation
