Repository elastic/apm-agent-python, pull requests merged in 2021-07, with the labels that each got.

#1163 make it possible to disable certifi
  docs/configuration.asciidoc
  elasticapm/conf/__init__.py
  elasticapm/transport/http.py
  tests/transports/test_urllib3.py
Labels: feature

#1174 Update test framework for starlette 0.15.0
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_framework_full.yml
  CHANGELOG.asciidoc
  elasticapm/contrib/starlette/__init__.py
  elasticapm/contrib/starlette/utils.py
  tests/contrib/asyncio/starlette_tests.py
  tests/requirements/reqs-starlette-0.13.txt
  tests/requirements/reqs-starlette-0.14.txt
  tests/requirements/reqs-starlette-newest.txt
Labels: agent-python

#1182 Fix redis supported technologies doc
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
Labels: agent-python

#1183 Fix isort lint for starlette_tests.py
  tests/contrib/asyncio/starlette_tests.py
Labels: agent-python

#1180 test: synchronizing json spec
  tests/upstream/json-specs/w3c_distributed_tracing.json
Labels: agent-python, automation

#1185 raise an exception for non-http scopes in the Starlette middleware
  elasticapm/contrib/starlette/__init__.py
Labels: agent-python

#1187 Fix Starlette/FastAPI middleware for non-http scopes
  CHANGELOG.asciidoc
  elasticapm/contrib/starlette/__init__.py
  tests/contrib/asyncio/starlette_tests.py
Labels: agent-python

#1190 ensure that the elasticsearch instrumentation handles DroppedSpans correctly
  elasticapm/instrumentation/packages/elasticsearch.py
  tests/instrumentation/elasticsearch_tests.py
Labels: agent-python

#1189 add aiofiles to starlette-0.14 requirements file
  tests/requirements/reqs-starlette-0.14.txt
Labels: agent-python

#1191 Mark `log_ecs_formatting` as experimental
  docs/configuration.asciidoc
Labels: agent-python

#1165 Prometheus histograms
  elasticapm/contrib/django/middleware/__init__.py
  elasticapm/metrics/base_metrics.py
  elasticapm/metrics/sets/prometheus.py
  tests/metrics/base_tests.py
  tests/metrics/prometheus_tests.py
Labels: agent-python

#1195 test: synchronizing json spec
  tests/upstream/json-specs/service_resource_inference.json
Labels: agent-python, automation

#1194 fetch server version on transport thread start
  elasticapm/base.py
  elasticapm/conf/constants.py
  elasticapm/transport/http.py
  elasticapm/transport/http_base.py
  tests/contrib/django/fixtures.py
  tests/fixtures.py
  tests/transports/test_urllib3.py
Labels: agent-python

#1196 limit the transport exception message to 10000 characters
  elasticapm/transport/http.py
Labels: agent-python

#1197 synchronize schema spec
  tests/upstream/json-specs/span.json
Labels: agent-python, automation
