Repository elastic/apm-agent-python, pull requests merged in 2021-04, with the labels that each got.

#1086 added docs for `transaction_ignore_urls`
  docs/configuration.asciidoc
Labels: agent-python

#1090 fix wrong destination nesting reported in #1088 and #1089
  elasticapm/instrumentation/packages/botocore.py
  tests/instrumentation/botocore_tests.py
Labels: agent-python

#1091 Validate every event created by the elasticapm_client test client
  elasticapm/contrib/tornado/utils.py
  tests/contrib/asyncio/tornado/tornado_tests.py
  tests/fixtures.py
Labels: agent-python

#1094 synchronize schema spec
  tests/upstream/json-specs/transaction.json
Labels: agent-python, automation

#1095 fall back on url_name and func name if no route name is provided with Django
  elasticapm/contrib/django/middleware/__init__.py
  tests/contrib/django/django_tests.py
  tests/contrib/django/testapp/nameless_route_urls.py
  tests/contrib/django/testapp/urls.py
Labels: agent-python

#1099 fix flask undefined client
  elasticapm/contrib/flask/__init__.py
Labels: agent-python

#1100 temporarily exclude pypy-3 from testing as it fails, possibly due to ecs-logging
  .ci/.jenkins_exclude.yml
Labels: agent-python

#1097 synchronize schema spec
  tests/upstream/json-specs/error.json
  tests/upstream/json-specs/metadata.json
  tests/upstream/json-specs/transaction.json
Labels: agent-python, automation

#1106 Update configuration.asciidoc
  docs/configuration.asciidoc
Labels: agent-python, docs

#1109 added item to release checklist for updating docs repo
  CONTRIBUTING.md
Labels: agent-python

#1113 exclude pypy-3/psycopg-2.7
  .ci/.jenkins_exclude.yml
Labels: agent-python

#1115 add database as a dependency in asyncpg instrumentation
  elasticapm/instrumentation/packages/asyncio/asyncpg.py
Labels: agent-python

#1117 Add drf Request support
  elasticapm/contrib/django/client.py
Labels: agent-python

#1118 Fix httpx 0.18.0
  elasticapm/instrumentation/packages/asyncio/httpcore.py
  elasticapm/instrumentation/packages/httpcore.py
  tests/instrumentation/asyncio_tests/httpx_tests.py
  tests/instrumentation/httpx_tests.py
Labels: agent-python

#1119 exclude old version of httpx on Python 3.10 as it fails
  .ci/.jenkins_exclude.yml
Labels: agent-python

#1120 fix warnings raised for pyodbc
  setup.cfg
  tests/instrumentation/pyodbc_tests.py
Labels: agent-python

#1121 try to use a virtualenv on Windows to fix dirty environment issues
  .ci/.jenkins_windows.yml
  scripts/install-tools.bat
  scripts/run-tests.bat
Labels: agent-python

#1122 implement azure app service cloud metadata collection
  elasticapm/utils/cloud.py
  tests/utils/cloud_tests.py
Labels: agent-python

#1123 implement specific instrumentation for AWS SQS
  docs/supported-technologies.asciidoc
  elasticapm/instrumentation/packages/botocore.py
  elasticapm/traces.py
  tests/instrumentation/botocore_tests.py
Labels: agent-python

#1082 Add aioredis instrumentation
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_framework.yml
  docs/supported-technologies.asciidoc
  elasticapm/instrumentation/packages/asyncio/aioredis.py
  elasticapm/instrumentation/register.py
  setup.cfg
  tests/instrumentation/asyncio_tests/aioredis_tests.py
  tests/requirements/reqs-aioredis-2.txt
  tests/requirements/reqs-aioredis-newest.txt
  tests/scripts/envs/aioredis.sh
Labels: agent-python
