Repository elastic/apm-agent-python, pull requests merged in 2021-03, with the labels that each got.

#1055 Use the new auto-synced json schema files
  CONTRIBUTING.md
  Makefile
  scripts/run-tests.bat
  tests/fixtures.py
  tests/scripts/download_json_schema.bat
  tests/scripts/download_json_schema.sh
  tests/scripts/run_tests.sh
  travis/run_tests.sh
Labels: agent-python

#1043 [WIP] Make Client object globally available
  CHANGELOG.asciidoc
  elasticapm/__init__.py
  elasticapm/base.py
  elasticapm/contrib/aiohttp/__init__.py
  elasticapm/contrib/aiohttp/middleware.py
  elasticapm/contrib/django/client.py
  elasticapm/contrib/flask/__init__.py
  elasticapm/contrib/opentracing/tracer.py
  elasticapm/contrib/paste.py
  elasticapm/contrib/pylons/__init__.py
  tests/contrib/django/django_tests.py
Labels: agent-python

#1058 Add `auto_ecs_logging` config
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  elasticapm/conf/__init__.py
  tests/fixtures.py
  tests/handlers/logging/logging_tests.py
  tests/requirements/reqs-base.txt
Labels: agent-python

#1065 Simplify client fetching in django.handlers.LoggingHandler
  elasticapm/contrib/django/handlers.py
Labels: agent-python

#1066 test: synchronizing gherkin spec
  tests/bdd/features/azure_app_service_metadata.feature
Labels: agent-python, automation

#1063 Refactor auto_ecs_logging to log_ecs_formatting
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  elasticapm/conf/__init__.py
  tests/handlers/logging/logging_tests.py
Labels: agent-python

#1068 Fix issue when resetting config after new value has been added
  CHANGELOG.asciidoc
  elasticapm/conf/__init__.py
  tests/config/tests.py
Labels: agent-python

#1072 delete last remnants of travis
  .travis.yml
  travis/run_tests.sh
Labels: agent-python

#1064 Django 3.2 support
  .ci/.jenkins_framework.yml
  .ci/.jenkins_framework_full.yml
  CHANGELOG.asciidoc
  elasticapm/contrib/django/apps.py
  tests/contrib/django/fixtures.py
  tests/contrib/django/testapp/urls.py
  tests/requirements/reqs-django-3.2.txt
Labels: agent-python

#1031 Add support for httplib2 (#1022)
  .ci/.jenkins_framework.yml
  .ci/.jenkins_framework_full.yml
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/httplib2.py
  elasticapm/instrumentation/register.py
  tests/instrumentation/httplib2_tests.py
  tests/requirements/reqs-httplib2-newest.txt
  tests/scripts/envs/httplib2.sh
Labels: agent-python

#1073 second attempt at fixing spurious test failures due to logs from background threads
  tests/client/client_tests.py
  tests/contrib/django/django_tests.py
  tests/instrumentation/base_tests.py
  tests/instrumentation/transactions_store_tests.py
  tests/metrics/base_tests.py
  tests/processors/tests.py
  tests/transports/test_base.py
  tests/utils/__init__.py
Labels: agent-python

#1076 Fix undefined routes
  CHANGELOG.asciidoc
  elasticapm/contrib/starlette/__init__.py
  tests/contrib/asyncio/starlette_tests.py
Labels: agent-python

#1077 add some more exclusions, and remove Python 2 from Makefile
  .ci/.jenkins_exclude.yml
  Makefile
Labels: agent-python

#1074 ci: use the new flaky analyser
  Jenkinsfile
Labels: agent-python, automation, ci

#1078 more eclusions due to collections.abc moves
  .ci/.jenkins_exclude.yml
Labels: agent-python

#1054 AWS specific instrumentations
  .editorconfig
  docs/supported-technologies.asciidoc
  elasticapm/instrumentation/packages/botocore.py
  tests/docker-compose.yml
  tests/instrumentation/botocore_tests.py
  tests/scripts/envs/boto3.sh
Labels: agent-python

#1079 use non-private attributes for service name and endpoint URL
  elasticapm/instrumentation/packages/botocore.py
Labels: agent-python

#1083 Prometheus metrics
  .ci/.jenkins_framework.yml
  docs/configuration.asciidoc
  docs/metrics.asciidoc
  elasticapm/base.py
  elasticapm/conf/__init__.py
  elasticapm/metrics/base_metrics.py
  elasticapm/metrics/sets/prometheus.py
  elasticapm/traces.py
  setup.cfg
  tests/metrics/base_tests.py
  tests/metrics/prometheus_tests.py
  tests/requirements/reqs-prometheus_client-newest.txt
  tests/scripts/envs/prometheus_client.sh
Labels: agent-python

#1084 update changelog and bump version to 6.1.0
  CHANGELOG.asciidoc
  elasticapm/version.py
Labels: agent-python
