Repository elastic/apm-agent-python, pull requests merged in 2021-11, with the labels that each got.

#1368 [WIP] More lambda improvements + docs
  CHANGELOG.asciidoc
  docs/api.asciidoc
  docs/serverless.asciidoc
  docs/set-up.asciidoc
  elasticapm/conf/constants.py
  elasticapm/contrib/serverless/aws.py
  elasticapm/traces.py
  elasticapm/utils/__init__.py
  tests/contrib/serverless/aws_api2_test_data.json
  tests/contrib/serverless/aws_tests.py
Labels: agent-python

#1379 synchronize schema spec
  tests/upstream/json-specs/error.json
Labels: automation, agent-python

#1377 decrement span_counter when span is compressed
  CHANGELOG.asciidoc
  elasticapm/traces.py
  tests/client/span_compression_tests.py
Labels: agent-python

#1374 delay initialization of urllib3 connection pool and reset on fork
  CHANGELOG.asciidoc
  elasticapm/transport/base.py
  elasticapm/transport/http.py
Labels: agent-python

#1378 Update User-Agent to match spec
  CHANGELOG.asciidoc
  elasticapm/base.py
  tests/client/client_tests.py
Labels: agent-python

#1382 More AWS Lambda improvements and spec changes
  CHANGELOG.asciidoc
  elasticapm/contrib/serverless/aws.py
  tests/contrib/serverless/aws_tests.py
Labels: agent-python

#1384 aiohttp exceptions can be normal responses
  CHANGELOG.asciidoc
  elasticapm/contrib/aiohttp/middleware.py
  tests/contrib/asyncio/aiohttp_web_tests.py
Labels: agent-python, community, triage

#1386 fix issue with multiple hosts/ports in psycopg2 connect span
  CHANGELOG.asciidoc
  elasticapm/base.py
  elasticapm/instrumentation/packages/psycopg2.py
  tests/fixtures.py
  tests/instrumentation/psycopg2_tests.py
Labels: agent-python

#1387 Remove socket.encrypted field
  CHANGELOG.asciidoc
  elasticapm/contrib/aiohttp/utils.py
  elasticapm/contrib/django/client.py
  elasticapm/contrib/flask/utils.py
  elasticapm/contrib/starlette/utils.py
  elasticapm/contrib/tornado/utils.py
  tests/contrib/asyncio/aiohttp_web_tests.py
  tests/contrib/asyncio/starlette_tests.py
  tests/contrib/asyncio/tornado/tornado_tests.py
Labels: agent-python

#1388 Remove transaction.breakdown.count and transaction metrics
  CHANGELOG.asciidoc
  docs/metrics.asciidoc
  elasticapm/metrics/sets/transactions.py
  elasticapm/traces.py
  tests/metrics/breakdown_tests.py
Labels: agent-python

#1392 remove aiohttp 4.0 from tests, as the last alpha is from 2019
  .ci/.jenkins_framework_full.yml
  tests/requirements/reqs-aiohttp-4.0.txt
Labels: agent-python

#1389 Cast transaction name to str
  CHANGELOG.asciidoc
  elasticapm/traces.py
  tests/instrumentation/transactions_store_tests.py
Labels: agent-python

#1394 sanic-20.12 requires an old uvloop version not supported in Python 3.10
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_python.yml
  setup.cfg
  tests/requirements/reqs-boto3-newest.txt
Labels: agent-python

#1397 remove TransactionsMetricSet from metrics settings
  elasticapm/conf/__init__.py
Labels: agent-python

#1395 chore: change the linting message to looks like the rest
  .ci/linting.groovy
  Jenkinsfile
Labels: agent-python

#1398 test: PR for testing messages
  Jenkinsfile
Labels: agent-python

#1403 refactor httpx instrumentation
  .ci/.jenkins_framework_full.yml
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/httpx/__init__.py
  elasticapm/instrumentation/packages/httpx/async/__init__.py
  elasticapm/instrumentation/packages/httpx/async/httpcore.py
  elasticapm/instrumentation/packages/httpx/async/httpx.py
  elasticapm/instrumentation/packages/httpx/sync/__init__.py
  elasticapm/instrumentation/packages/httpx/sync/httpcore.py
  elasticapm/instrumentation/packages/httpx/sync/httpx.py
  elasticapm/instrumentation/packages/httpx/utils.py
  elasticapm/instrumentation/register.py
  tests/requirements/reqs-httpx-0.21.txt
  tests/requirements/reqs-httpx-newest.txt
Labels: agent-python

#1407 fix default value for span_compression_exact_match_max_duration
  CHANGELOG.asciidoc
  elasticapm/conf/__init__.py
Labels: agent-python

#1414 Filter Sanic config object to only include configration values in context
  elasticapm/contrib/sanic/utils.py
Labels: agent-python, community, triage

#1416 Shorten long SQL query to prevent oversized event
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/asyncio/asyncpg.py
  tests/instrumentation/asyncio_tests/asyncpg_tests.py
Labels: agent-python, community, triage

#1417 Unify async_capture_span/capture_span common code
  elasticapm/contrib/asyncio/traces.py
  elasticapm/traces.py
Labels: agent-python

#1419 chore(ci): use filebeat step to archive docker container logs
  Jenkinsfile
  tests/scripts/docker/docker-summary.sh
  tests/scripts/docker/run_tests.sh
Labels: ci, chore, Team:Automation, agent-python
