Repository elastic/apm-agent-python, pull requests merged in 2021-12, with the labels that each got.

#1420 fix pymongo 4.0 test failures
  elasticapm/instrumentation/packages/pymongo.py
  tests/instrumentation/pymongo_tests.py
Labels: agent-python

#1418 implement dropping of fast exit spans
  docs/configuration.asciidoc
  elasticapm/conf/__init__.py
  elasticapm/traces.py
  tests/client/dropped_spans_tests.py
  tests/config/tests.py
  tests/contrib/django/fixtures.py
  tests/fixtures.py
  tests/instrumentation/transactions_store_tests.py
Labels: agent-python

#1426 test: synchronizing json spec
  tests/upstream/json-specs/span_types.json
Labels: automation, agent-python

#1421 test: synchronizing gherkin spec
  tests/bdd/features/api_key.feature
  tests/bdd/features/azure_app_service_metadata.feature
  tests/bdd/features/outcome.feature
  tests/bdd/features/user_agent.feature
Labels: automation, agent-python

#1423 Fix AttributeError in sync httpx instrumentation
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/httpx/sync/httpcore.py
Labels: agent-python, community

#1436 fix casing of exit_span_min_duration setting
  elasticapm/conf/__init__.py
Labels: agent-python

#1437 ci: update opbeans branch to main
  Jenkinsfile
Labels: agent-python
