Repository elastic/apm-agent-python, pull requests merged in 2021-02, with the labels that each got.

#1034 Remove tags (deprecated) + Update docs for 6.x
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  elasticapm/__init__.py
  elasticapm/traces.py
  tests/client/client_tests.py
  tests/client/exception_tests.py
  tests/instrumentation/transactions_store_tests.py
Labels: agent-python, breaking change

#1035 with Python 2 support gone, we can update a bunch of requirements
  tests/requirements/reqs-base.txt
  tests/transports/test_urllib3.py
Labels: agent-python

#1033 fix distributed tracing header injection when directly using HTTPConnectionPool
  elasticapm/instrumentation/packages/urllib3.py
  tests/instrumentation/urllib3_tests.py
Labels: agent-python, bug

#1038 Fix for hang on capture_body: error in starlette
  CHANGELOG.asciidoc
  elasticapm/contrib/starlette/__init__.py
  elasticapm/contrib/starlette/utils.py
  tests/contrib/asyncio/starlette_tests.py
Labels: agent-python

#1039 updated test matrix and supported technologies docs
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_framework.yml
  .ci/.jenkins_framework_full.yml
  docs/supported-technologies.asciidoc
  setup.cfg
  tests/requirements/reqs-django-1.10.txt
  tests/requirements/reqs-django-1.8.txt
  tests/requirements/reqs-django-1.9.txt
  tests/requirements/reqs-django-3.1.txt
Labels: agent-python

#1044 [CI] Use the releaseNotification step
  Jenkinsfile
Labels: agent-python, automation, ci

#1042 Add defaults for all required config values
  docs/configuration.asciidoc
  elasticapm/base.py
  elasticapm/conf/__init__.py
  tests/contrib/django/django_tests.py
Labels: agent-python

#1041 Send request body as a string in Starlette
  CHANGELOG.asciidoc
  elasticapm/contrib/starlette/utils.py
  tests/contrib/asyncio/starlette_tests.py
Labels: agent-python

#1012 Only process frames if they exist
  CHANGELOG.asciidoc
  elasticapm/traces.py
Labels: agent-python

#1048 test: synchronizing gherkin spec
  tests/bdd/features/outcome.feature
Labels: agent-python, automation

#1037 Fix transaction names for starlette Mount routes
  CHANGELOG.asciidoc
  elasticapm/contrib/starlette/__init__.py
  tests/contrib/asyncio/starlette_tests.py
Labels: agent-python

#1051 Fix starlette/fastapi hang on capture_body
  elasticapm/contrib/starlette/utils.py
Labels: agent-python

#1053 synchronize schema spec
  tests/upstream/json-specs/error.json
  tests/upstream/json-specs/metadata.json
  tests/upstream/json-specs/metricset.json
  tests/upstream/json-specs/span.json
  tests/upstream/json-specs/transaction.json
Labels: agent-python, automation
