Repository elastic/apm-agent-python, pull requests merged in 2021-01, with the labels that each got.

#995 remove Python 3.5 on Windows testing
  .ci/.jenkins_windows.yml
  scripts/install-tools.bat
Labels: agent-python

#994 properly support already-encoded SQL strings with psycopg2
  elasticapm/instrumentation/packages/psycopg2.py
  tests/instrumentation/psycopg2_tests.py
Labels: agent-python

#996 Adding auto option to the description of cloud_provider config
  docs/configuration.asciidoc
Labels: agent-python

#999 Revert "pin pip to 20.3.1 due to a bug in 20.3.2 (#989)"
  scripts/install-tools.bat
  tests/Dockerfile
  tests/scripts/docker/black.sh
  tests/scripts/docker/flake8.sh
  tests/scripts/docker/isort.sh
  tests/scripts/run_tests.sh
Labels: agent-python

#998 Fix for json-incompatible elasticsearch bodies
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/elasticsearch.py
  tests/instrumentation/asyncio_tests/async_elasticsearch_client_tests.py
  tests/instrumentation/elasticsearch_tests.py
Labels: agent-python

#1001 Fix python-memcached package name
  docs/supported-technologies.asciidoc
Labels: agent-python

#1000 Fix starlette to not instrument when enabled=False
  .pre-commit-config.yaml
  CHANGELOG.asciidoc
  elasticapm/contrib/starlette/__init__.py
  tests/contrib/asyncio/starlette_tests.py
Labels: agent-python

#1003 Fix test fixtures to uninstrument
  tests/contrib/asyncio/aiohttp_web_tests.py
  tests/contrib/asyncio/tornado/tornado_tests.py
  tests/contrib/django/fixtures.py
  tests/contrib/flask/fixtures.py
  tests/contrib/opentracing/tests.py
Labels: agent-python

#1014 Add service.name to logging integrations
  elasticapm/handlers/logging.py
  elasticapm/handlers/structlog.py
  tests/handlers/logging/logging_tests.py
Labels: agent-python

#1015 Fix GraphQL instrumentation: span spamming
  elasticapm/instrumentation/packages/graphql.py
  tests/instrumentation/graphql_tests.py
Labels: agent-python

#1011 Add `use_elastic_excepthook` to docs
  docs/configuration.asciidoc
Labels: agent-python

#1016 make certifi import optional
  elasticapm/transport/http.py
Labels: agent-python

#1017 Update sanitizing-data.asciidoc
  docs/sanitizing-data.asciidoc
Labels: agent-python

#1021 Remove support for python2, pypy2, and python 3.5
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_python.yml
  CHANGELOG.asciidoc
  Jenkinsfile
  elasticapm/__init__.py
  setup.cfg
Labels: agent-python, breaking change

#1013 align elasticsearch body capturing with other agents
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/asyncio/elasticsearch.py
  elasticapm/instrumentation/packages/elasticsearch.py
  elasticapm/instrumentation/register.py
  tests/instrumentation/asyncio_tests/async_elasticsearch_client_tests.py
  tests/instrumentation/elasticsearch_tests.py
Labels: agent-python, breaking change

#982 [META 319] Align sanitize_field_names with cross-agent spec
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  docs/sanitizing-data.asciidoc
  elasticapm/conf/__init__.py
  elasticapm/conf/constants.py
  elasticapm/processors.py
  tests/processors/tests.py
Labels: agent-python, breaking change, feature
