Repository elastic/apm-agent-python, pull requests merged in 2022-09, with the labels that each got.

#1625 Add AWS Request ID to botocore span context
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/asyncio/aiobotocore.py
  elasticapm/instrumentation/packages/botocore.py
  tests/instrumentation/botocore_tests.py
Labels: agent-python

#1628 Fix empty flushed=True request for forced flushes
  CHANGELOG.asciidoc
  elasticapm/transport/base.py
  tests/transports/test_base.py
Labels: agent-python

#1630 synchronize schema spec
  tests/upstream/json-specs/log.json
Labels: automation, agent-python

#1632 Disable checks when elastic_apm is disabled
  CHANGELOG.asciidoc
  elasticapm/contrib/django/management/commands/elasticapm.py
  tests/contrib/django/django_tests.py
Labels: agent-python, community, triage

#1635 Doesn"t cut request body with size >= 10000
  CHANGELOG.asciidoc
  elasticapm/contrib/starlette/__init__.py
  tests/contrib/asyncio/starlette_tests.py
Labels: agent-python, community, triage

#1637 properly set transaction outcome
  CHANGELOG.asciidoc
  elasticapm/contrib/flask/__init__.py
Labels: agent-python, community, triage

#1640 No issue: Fix APP_NAME references
  docs/sanitizing-data.asciidoc
  elasticapm/contrib/flask/__init__.py
  elasticapm/contrib/starlette/__init__.py
Labels: agent-python, community, triage

#1644 .ci: remove Integration Tests stage
  Jenkinsfile
Labels: agent-python

#1642 Elasticsearch 8 support
  .ci/.jenkins_framework.yml
  .ci/.jenkins_framework_full.yml
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/asyncio/elasticsearch.py
  elasticapm/instrumentation/packages/elasticsearch.py
  tests/docker-compose.yml
  tests/instrumentation/asyncio_tests/async_elasticsearch_client_tests.py
  tests/instrumentation/elasticsearch_tests.py
  tests/requirements/reqs-elasticsearch-8.txt
  tests/scripts/envs/elasticsearch-8.sh
Labels: agent-python

#1646 test: synchronizing json spec
  tests/upstream/json-specs/cgroup_parsing.json
Labels: automation, agent-python
