Repository elastic/apm-agent-python, pull requests merged in 2022-07, with the labels that each got.

#1581 ci: use the microbenchmarks-pool
  Jenkinsfile
Labels: automation, Team:Automation, agent-python

#1582 docs: consistent naming of APM AWS Lambda extension
  docs/serverless.asciidoc
Labels: agent-python, Team:Docs

#1584 test: synchronizing gherkin spec
  tests/bdd/features/otel_bridge.feature
Labels: automation, agent-python

#1590 Fix exception for bad port in Django request
  elasticapm/contrib/django/client.py
  tests/contrib/django/django_tests.py
Labels: agent-python

#1591 cast redis ports to int
  elasticapm/instrumentation/packages/asyncio/aioredis.py
  elasticapm/instrumentation/packages/redis.py
Labels: agent-python, community, triage

#1593 Fix varmap to apply func before recursion
  CHANGELOG.asciidoc
  elasticapm/utils/__init__.py
Labels: agent-python

#1594 Simplify logic in varmap
  elasticapm/utils/__init__.py
Labels: agent-python

#1596 label no longer fails when called without a client
  elasticapm/traces.py
  tests/client/client_tests.py
Labels: agent-python, community, triage
