Repository elastic/apm-agent-python, pull requests merged in 2022-04, with the labels that each got.

#1511 Improved lambda getting started docs
  docs/lambda/configure-lambda-widget.asciidoc
  docs/lambda/configure-lambda.asciidoc
  docs/serverless.asciidoc
Labels: agent-python

#1516 ci: packer_cache never fail
  .ci/packer_cache.sh
Labels: automation, Team:Automation, agent-python

#1518 Fix sanic tests
  tests/contrib/sanic/fixtures.py
  tests/contrib/sanic/sanic_tests.py
Labels: agent-python

#1521 Fix sanic tests for 20.12.x
  tests/contrib/sanic/sanic_tests.py
Labels: agent-python

#1520 Add instrumentation for aiobotocore
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_framework.yml
  .ci/.jenkins_framework_full.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  elasticapm/instrumentation/packages/asyncio/aiobotocore.py
  elasticapm/instrumentation/packages/botocore.py
  elasticapm/instrumentation/register.py
  setup.cfg
  tests/instrumentation/asyncio_tests/aiobotocore_tests.py
  tests/requirements/reqs-aiobotocore-newest.txt
  tests/scripts/envs/aiobotocore.sh
Labels: agent-python, community, triage

#1526 some black fixes
  elasticapm/base.py
  elasticapm/contrib/django/handlers.py
  elasticapm/utils/compat.py
  elasticapm/utils/encoding.py
  tests/contrib/django/django_tests.py
  tests/instrumentation/asyncio_tests/aiobotocore_tests.py
  tests/instrumentation/mysql_tests.py
  tests/instrumentation/transactions_store_tests.py
  tests/metrics/cpu_psutil_tests.py
  tests/processors/tests.py
  tests/utils/encoding/tests.py
Labels: agent-python

#1529 synchronize schema spec
  tests/upstream/json-specs/error.json
  tests/upstream/json-specs/span.json
  tests/upstream/json-specs/transaction.json
Labels: automation, agent-python

#1530 Fix missing return in opentelemetry.Span.is_recording
  CHANGELOG.asciidoc
  elasticapm/contrib/opentelemetry/span.py
Labels: agent-python

#1531 synchronize schema spec
  tests/upstream/json-specs/error.json
  tests/upstream/json-specs/span.json
  tests/upstream/json-specs/transaction.json
Labels: automation, agent-python

#1532 packer_cache: avoid failing
  .ci/packer_cache.sh
Labels: agent-python

#1535 ci: use coverageReport for code coverage
  Jenkinsfile
Labels: agent-python

#1536 Conditionally log warning when adding labels
  elasticapm/traces.py
  tests/instrumentation/transactions_store_tests.py
  tests/utils/__init__.py
Labels: agent-python, community, triage
