Repository elastic/apm-agent-python, pull requests merged in 2022-01, with the labels that each got.

#1438 use "unknown-python-service" as default service name
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  elasticapm/conf/__init__.py
Labels: agent-python

#1443 ci: use the apm-its/main branch
  Jenkinsfile
Labels: agent-python

#1439 synchronize schema spec
  tests/upstream/json-specs/transaction.json
Labels: automation, agent-python

#1441 add transaction name to error objects
  CHANGELOG.asciidoc
  elasticapm/base.py
  elasticapm/contrib/django/middleware/__init__.py
  tests/contrib/django/django_tests.py
  tests/contrib/django/testapp/urls.py
Labels: agent-python

#1442 Drop non sampled transactions
  CHANGELOG.asciidoc
  elasticapm/base.py
  elasticapm/traces.py
  tests/client/client_tests.py
  tests/client/transaction_tests.py
  tests/contrib/django/django_tests.py
  tests/instrumentation/asyncio_tests/aiohttp_client_tests.py
  tests/instrumentation/transactions_store_tests.py
  tests/instrumentation/urllib3_tests.py
  tests/instrumentation/urllib_tests.py
Labels: agent-python

#1431 implement snapshotting of certain configuration during transaction lifetime
  CHANGELOG.asciidoc
  elasticapm/conf/__init__.py
  elasticapm/traces.py
  tests/client/span_compression_tests.py
  tests/config/config_snapshotting_tests.py
  tests/instrumentation/transactions_store_tests.py
Labels: agent-python

#1444 Fix span compression for redis et. al.
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/cassandra.py
  elasticapm/instrumentation/packages/pylibmc.py
  elasticapm/instrumentation/packages/pymemcache.py
  elasticapm/instrumentation/packages/pymongo.py
  elasticapm/instrumentation/packages/python_memcached.py
  elasticapm/traces.py
  tests/instrumentation/cassandra_tests.py
  tests/instrumentation/pymemcache_tests.py
  tests/instrumentation/pymongo_tests.py
  tests/instrumentation/python_memcached_tests.py
  tests/instrumentation/redis_tests.py
Labels: agent-python

#1371 Django Celery trace.id integration
  CHANGELOG.asciidoc
  docs/django.asciidoc
  elasticapm/contrib/celery/__init__.py
Labels: agent-python, community

#1445 use a limited amount of Python versions for PR runs
  .ci/.jenkins_python.yml
  .ci/.jenkins_python_full.yml
  .ci/nightly.groovy
  .ci/packer_cache.sh
  Jenkinsfile
Labels: agent-python

#1447 Neutral naming: main
  .ci/jobs/apm-agent-python-mbp.yml
  .ci/jobs/apm-agent-python-nightly-mbp.yml
  CONTRIBUTING.md
  Jenkinsfile
  README.rst
  docs/run-tests-locally.asciidoc
  elasticapm/instrumentation/packages/azure.py
Labels: agent-python

#1450 [6.x] Doc link fixes
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/getting-started.asciidoc
  docs/opentracing.asciidoc
Labels: agent-python

#1451 [5.x] Doc link fixes
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/getting-started.asciidoc
  docs/opentracing.asciidoc
Labels: agent-python
