Repository elastic/apm-agent-python, pull requests merged in 2022-11, with the labels that each got.

#1687 Handle track_total_hits=False in elasticsearch instrumentation
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/elasticsearch.py
  tests/instrumentation/elasticsearch_tests.py
Labels: agent-python

#1690 Use span.update_context to avoid DroppedSpan issues in Elasticsearch instrumentation
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/elasticsearch.py
Labels: agent-python

#1696 Exclude pymssql tests for python 3.6
  .ci/.jenkins_exclude.yml
Labels: agent-python

#1695 Fix parent_id was missed when logging under leaf span
  elasticapm/base.py
Labels: agent-python, community, triage

#1692 Lower log level for server version problems
  elasticapm/transport/http.py
  tests/transports/test_urllib3.py
Labels: agent-python

#1699 synchronize schema spec
  tests/upstream/json-specs/span.json
Labels: automation, agent-python

#1702 test: synchronizing json spec
  tests/upstream/json-specs/service_resource_inference.json
Labels: automation, agent-python
