Repository elastic/apm-agent-python, pull requests merged in 2022-10, with the labels that each got.

#1653 fix starlette 0.21 tests
  .ci/.jenkins_framework.yml
  tests/contrib/asyncio/starlette_tests.py
  tests/requirements/reqs-starlette-newest.txt
Labels: agent-python

#1651 only use content-type and content-encoding headers for POSTing events
  elasticapm/base.py
  elasticapm/transport/http.py
  tests/transports/test_urllib3.py
Labels: agent-python

#1648 fix errors in pymongo tests introduced in #1639
  elasticapm/instrumentation/packages/pymongo.py
  tests/instrumentation/pymongo_tests.py
Labels: agent-python

#1652 Use minimum of 5 seconds for interval between central config calls
  elasticapm/transport/http.py
  tests/transports/test_urllib3.py
Labels: agent-python

#1655 Use typing.TypeVar on decorators' type hints
  elasticapm/contrib/asyncio/traces.py
  elasticapm/contrib/serverless/aws.py
  elasticapm/traces.py
  elasticapm/utils/compat.py
  elasticapm/utils/deprecation.py
Labels: agent-python, community, triage

#1663 chore: remove unused scripts for linting and update docs
  docs/run-tests-locally.asciidoc
  tests/scripts/docker/black.sh
  tests/scripts/docker/flake8.sh
  tests/scripts/docker/isort.sh
Labels: automation, Team:Automation, agent-python

#1643 Collect metrics once per lambda invocation
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  docs/metrics.asciidoc
  elasticapm/base.py
  elasticapm/contrib/serverless/aws.py
  elasticapm/metrics/base_metrics.py
  elasticapm/metrics/sets/cpu_linux.py
  elasticapm/metrics/sets/cpu_psutil.py
  elasticapm/metrics/sets/prometheus.py
  elasticapm/traces.py
  tests/client/dropped_spans_tests.py
  tests/metrics/base_tests.py
  tests/metrics/breakdown_tests.py
Labels: agent-python

#1647 validate JSON types/subtypes
  elasticapm/instrumentation/packages/asyncio/aiopg.py
  tests/fixtures.py
  tests/instrumentation/asyncio_tests/aiopg_tests.py
  tests/utils/span_type_subtype_tests.py
Labels: agent-python

#1670 EOL table has been moved to central EOL Policy page
  CONTRIBUTING.md
  docs/upgrading.asciidoc
Labels: agent-python

#1662 add span links from SQS messages in AWS lambda transactions
  CHANGELOG.asciidoc
  elasticapm/base.py
  elasticapm/contrib/serverless/aws.py
  tests/contrib/serverless/aws_sqs_test_data.json
  tests/contrib/serverless/aws_tests.py
Labels: agent-python

#1671 Correct links to Lambda extension docs
  docs/lambda/configure-lambda.asciidoc
  docs/serverless.asciidoc
Labels: agent-python

#1678 unvendor wrapt
  Jenkinsfile
  elasticapm/contrib/django/middleware/__init__.py
  elasticapm/handlers/logging.py
  elasticapm/instrumentation/packages/base.py
  elasticapm/instrumentation/packages/dbapi2.py
  elasticapm/utils/wrapt/LICENSE
  elasticapm/utils/wrapt/__init__.py
  elasticapm/utils/wrapt/_wrappers.c
  elasticapm/utils/wrapt/arguments.py
  elasticapm/utils/wrapt/decorators.py
  elasticapm/utils/wrapt/importer.py
  elasticapm/utils/wrapt/wrappers.py
  setup.cfg
  setup.py
  tests/contrib/asyncio/starlette_tests.py
  tests/contrib/asyncio/tornado/tornado_tests.py
  tests/instrumentation/base_tests.py
  tests/requirements/reqs-base.txt
Labels: agent-python

#1677 synchronize schema spec
  tests/upstream/json-specs/error.json
  tests/upstream/json-specs/span.json
  tests/upstream/json-specs/transaction.json
Labels: automation, agent-python

#1674 Add starlette ServerErrorMiddleware instrumentation
  CHANGELOG.asciidoc
  elasticapm/contrib/starlette/__init__.py
  elasticapm/instrumentation/packages/asyncio/starlette.py
  elasticapm/instrumentation/register.py
  tests/contrib/asyncio/starlette_tests.py
Labels: agent-python

#1668 sync async_capture_span docs with capture_span
  docs/api.asciidoc
Labels: agent-python

#1680 Python 3.11 support, and matrix cleanup
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_framework.yml
  .ci/.jenkins_framework_full.yml
  .ci/.jenkins_python.yml
  .ci/.jenkins_python_full.yml
  Makefile
  setup.cfg
  tests/instrumentation/pymssql_tests.py
  tests/requirements/reqs-base.txt
  tests/requirements/reqs-memcached-1.51.txt
  tests/requirements/reqs-pymongo-2.9.txt
  tests/requirements/reqs-pymongo-3.0.txt
  tests/requirements/reqs-pymssql-newest.txt
  tests/requirements/reqs-twisted-newest.txt
Labels: agent-python

#1673 add context.db.instance to elasticsearch spans
  elasticapm/instrumentation/packages/elasticsearch.py
  tests/instrumentation/elasticsearch_tests.py
Labels: agent-python

#1683 Remove twine upload for (now-removed) wheels
  Jenkinsfile
Labels: agent-python
