Repository elastic/apm-agent-python, pull requests merged in 2022-03, with the labels that each got.

#1470 Move the APM server fetch log to `debug`
  elasticapm/transport/http.py
Labels: agent-python

#1471 synchronize schema spec
  tests/upstream/json-specs/transaction.json
Labels: automation, agent-python

#1475 Fix inconsistent case for `API_KEY` config in docs
  docs/configuration.asciidoc
Labels: agent-python

#1483 Fix exit_span_min_duration to properly use ms
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  elasticapm/conf/__init__.py
  elasticapm/traces.py
  tests/client/dropped_spans_tests.py
  tests/config/config_snapshotting_tests.py
Labels: agent-python

#1453 jjbb: remove periodic trigger
  .ci/jobs/apm-agent-python-linting-mbp.yml
  .ci/jobs/apm-agent-python-mbp.yml
  .ci/jobs/apm-agent-python-nightly-mbp.yml
Labels: automation, agent-python

#1490 test: synchronizing gherkin spec
  tests/bdd/features/otel_bridge.feature
Labels: automation, agent-python

#1491 synchronize schema spec
  tests/upstream/json-specs/span.json
  tests/upstream/json-specs/transaction.json
Labels: automation, agent-python

#1489 Lambda improvements
  CHANGELOG.asciidoc
  elasticapm/contrib/serverless/aws.py
  elasticapm/transport/base.py
  elasticapm/transport/http.py
  elasticapm/transport/http_base.py
  tests/contrib/serverless/aws_sns_test_data.json
  tests/contrib/serverless/aws_sqs_test_data.json
  tests/contrib/serverless/aws_tests.py
  tests/transports/test_base.py
Labels: agent-python

#1503 work around issue with older flask versions and newest jinja2 release
  setup.cfg
  tests/requirements/reqs-flask-1.0.txt
  tests/requirements/reqs-flask-1.1.txt
Labels: agent-python

#1505 pypy tests fail with an SQLite error message on pypy
  .ci/.jenkins_python_full.yml
Labels: agent-python

#1501 test: synchronizing gherkin spec
  tests/bdd/features/otel_bridge.feature
Labels: automation, agent-python

#1498 Span stack trace min duration
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  docs/tuning.asciidoc
  elasticapm/conf/__init__.py
  elasticapm/traces.py
  tests/client/transaction_tests.py
  tests/contrib/django/fixtures.py
  tests/fixtures.py
  tests/utils/stacks/tests.py
Labels: agent-python

#1504 Enable span compression by default
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  elasticapm/conf/__init__.py
Labels: agent-python

#1500 Celery contrib: read custom parent span id from the task headers
  CHANGELOG.asciidoc
  elasticapm/contrib/celery/__init__.py
Labels: agent-python, community, triage

#1508 limit Werkzeug version for older Flask versions
  tests/requirements/reqs-flask-1.0.txt
  tests/requirements/reqs-flask-1.1.txt
Labels: agent-python

#1512 Add back opentracing docs
  docs/opentracing.asciidoc
Labels: agent-python

#1510 fix issue in span serialization when using APM Server < 7.16
  CHANGELOG.asciidoc
  elasticapm/traces.py
  tests/client/transaction_tests.py
Labels: agent-python

#1513 Add doc redirects
  docs/index.asciidoc
  docs/opentracing.asciidoc
  docs/redirects.asciidoc
Labels: agent-python
