Repository elastic/apm-agent-python, pull requests merged in 2022-05, with the labels that each got.

#1542 linting: use the GIT_BASE_COMMIT env variable
  .ci/linting.groovy
Labels: agent-python

#1543 Fix otel bridge span destination resource
  elasticapm/contrib/opentelemetry/span.py
Labels: agent-python

#1551 synchronize schema spec
  tests/upstream/json-specs/span.json
  tests/upstream/json-specs/transaction.json
Labels: automation, agent-python

#1553 synchronize schema spec
  tests/upstream/json-specs/error.json
  tests/upstream/json-specs/span.json
  tests/upstream/json-specs/transaction.json
Labels: automation, agent-python

#1558 UnicodeDecodeError_starlette_fix
  elasticapm/contrib/starlette/utils.py
Labels: agent-python, community, triage
