Repository elastic/apm-agent-python, pull requests merged in 2023-02, with the labels that each got.

#1738 Copy dict before iterating in encoding.transform
  elasticapm/utils/encoding.py
Labels: agent-python, community, triage

#1731 Migrate Jenkinsfile 2 GH Actions Workflow
  .ci/.jenkins_exclude.yml
  .ci/.matrix_exclude.yml
  .ci/.matrix_framework.yml
  .ci/.matrix_framework_full.yml
  .ci/.matrix_python.yml
  .ci/.matrix_python_full.yml
  .ci/.matrix_windows.yml
  .ci/jobs/apm-agent-python-mbp.yml
  .ci/nightly.groovy
  .ci/snapshoty.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/packages.yml
  .github/workflows/release.yml
  .github/workflows/snapshoty.yml
  .github/workflows/test-reporter.yml
  .github/workflows/test.yml
  Jenkinsfile
  Makefile
  conftest.py
  scripts/install-tools.bat
  scripts/run-tests.bat
  tests/scripts/docker/run_tests.sh
  tests/scripts/run_tests.sh
Labels: agent-python, community, triage

#1744 Change `server_url` default to avoid ipv6 ambiguity
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  docs/django.asciidoc
  elasticapm/conf/__init__.py
  tests/contrib/django/django_tests.py
Labels: agent-python

#1743 Add service.agent.activation_method to metadata
  CHANGELOG.asciidoc
  elasticapm/base.py
  tests/client/client_tests.py
Labels: agent-python

#1747 Fix nightly scheduled test
  .github/workflows/run-matrix.yml
  .github/workflows/test.yml
Labels: agent-python, community, triage

#1745 Add update-specs updatcli workflow
  .ci/update-specs.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/update-specs.yml
Labels: agent-python, community, triage

#1749 Required Status Check
  .github/workflows/test.yml
  scripts/run-tests.bat
Labels: agent-python, community, triage

#1753 Set status check to success in case it's an only-docs PR
  .github/workflows/test-docs.yml
  .github/workflows/test.yml
Labels: agent-python, community, triage

#1752 Update badge
  README.rst
Labels: agent-python, community, triage

#1751 Added the psutil command with the elastic-apm[flask] installation to avoid metrics error
  .pre-commit-config.yaml
  docs/flask.asciidoc
Labels: agent-python, community, triage

#1750 Add dynamic config tag to more supported options
  docs/configuration.asciidoc
Labels: docs, agent-python

#1758 Fix async elasticsearch to match #1690
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/asyncio/elasticsearch.py
Labels: agent-python

#1756 Use composite action for updatecli workflow
  .github/workflows/update-specs.yml
Labels: agent-python, community, triage

#1762 jjbb: filter by v tags
  .ci/jobs/apm-agent-python-mbp.yml
Labels: agent-python
