Repository elastic/apm-agent-python, pull requests merged in 2023-05, with the labels that each got.

#1822 Fix tests for urllib3 v2.0.1+
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/urllib3.py
  setup.cfg
  tests/client/client_tests.py
  tests/client/exception_tests.py
  tests/instrumentation/urllib3_tests.py
  tests/requirements/reqs-base.txt
Labels: agent-python

#1823 [Automation] Update Gherkin specs
  tests/bdd/features/otel_bridge.feature
Labels: automation, agent-python

#1821 Update the tests_require block to match reqs-base.txt
  setup.cfg
Labels: agent-python

#1818 Update partial transaction failure handling and add a test
  elasticapm/contrib/serverless/aws.py
  tests/contrib/serverless/aws_tests.py
Labels: agent-python

#1831 docs-ci: brief summary about the CI
  .github/workflows/README.md
Labels: agent-python

#1829 ci: enable microbenchmark
  .ci/bench.sh
  .ci/jobs/apm-agent-python-mbp.yml
  .ci/jobs/apm-agent-python.yml
  .ci/jobs/defaults.yml
  .ci/packer_cache.sh
  .editorconfig
  .github/workflows/microbenchmark.yml
  CONTRIBUTING.md
  Jenkinsfile
Labels: agent-python

#1814 Lambda layer release automation
  .ci/create-arn-table.sh
  .ci/publish-aws.sh
  .github/workflows/build-distribution.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
Labels: agent-python, community, triage

#1830 add wrapper support for Starlette
  CHANGELOG.asciidoc
  docs/wrapper.asciidoc
  elasticapm/instrumentation/packages/starlette.py
  elasticapm/instrumentation/register.py
  tests/instrumentation/starlette_tests.py
Labels: agent-python
