Repository elastic/apm-agent-python, pull requests merged in 2023-01, with the labels that each got.

#1716 synchronize schema spec
  tests/upstream/json-specs/metadata.json
  tests/upstream/json-specs/span.json
  tests/upstream/json-specs/transaction.json
Labels: automation, agent-python

#1713 Add docs note about setup code in lambda
  .ci/.jenkins_framework_full.yml
  CHANGELOG.asciidoc
  docs/serverless.asciidoc
Labels: agent-python

#1723 test: synchronizing gherkin spec
  tests/bdd/features/azure_functions_metadata.feature
Labels: automation, agent-python

#1724 action: use opentelemetry composite action
  .github/workflows/opentelemetry.yml
Labels: automation, Team:Automation, agent-python

#1720 Config docs update with note for AWS Lambda
  docs/configuration.asciidoc
Labels: agent-python, community, triage

#1725 Properly await wrapped async call in elasticsearch
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/asyncio/elasticsearch.py
Labels: agent-python

#1709 [WIP] Wrapper script
  CHANGELOG.asciidoc
  docs/set-up.asciidoc
  docs/wrapper.asciidoc
  elasticapm/base.py
  elasticapm/instrumentation/packages/flask.py
  elasticapm/instrumentation/register.py
  elasticapm/instrumentation/wrapper/__init__.py
  elasticapm/instrumentation/wrapper/__main__.py
  elasticapm/instrumentation/wrapper/sitecustomize.py
  setup.cfg
  tests/client/transaction_tests.py
  tests/contrib/flask/fixtures.py
  tests/contrib/flask/flask_tests.py
  tests/fixtures.py
  tests/instrumentation/flask_tests.py
  tests/instrumentation/wrapper/__init__.py
  tests/instrumentation/wrapper/testapp.py
  tests/instrumentation/wrapper/wrapper_tests.py
  tests/requirements/reqs-base.txt
Labels: agent-python

#1729 Fix some deprecation warnings that were missed in the 6.0.0 release
  elasticapm/base.py
  tests/client/client_tests.py
Labels: agent-python

#1728 fix: "tracestate" parsing must allow whitespace around list-members
  CHANGELOG.asciidoc
  elasticapm/utils/disttracing.py
  tests/utils/test_disttracing_header.py
Labels: agent-python

#1727 Fix lambda performance issue
  CHANGELOG.asciidoc
  docs/serverless.asciidoc
  elasticapm/contrib/serverless/aws.py
  tests/contrib/serverless/aws_tests.py
Labels: agent-python

#1732 Minor copyedits to the changelog and wrapper docs
  CHANGELOG.asciidoc
  docs/wrapper.asciidoc
Labels: agent-python
