Repository elastic/apm-agent-python, pull requests merged in 2023-06, with the labels that each got.

#1842 [doc] add missing 6.x release notes link
  docs/release-notes.asciidoc
Labels: agent-python

#1840 Add ecs_logging to dependencies
  CHANGELOG.asciidoc
  docs/logging.asciidoc
  setup.cfg
Labels: agent-python

#1841 Support Psycopg3 synchronous operations
  .ci/.matrix_framework.yml
  .ci/.matrix_framework_full.yml
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/psycopg.py
  elasticapm/instrumentation/register.py
  tests/instrumentation/psycopg_tests.py
  tests/requirements/reqs-psycopg-newest.txt
  tests/scripts/envs/psycopg.sh
Labels: agent-python, community, triage

#1844 update CHANGELOG and bump version to 6.16.0
  CHANGELOG.asciidoc
  CONTRIBUTING.md
  elasticapm/version.py
Labels: agent-python

#1845 Fix release workflow
  .ci/publish-aws.sh
  .github/workflows/release.yml
Labels: agent-python, community, triage

#1846 update CHANGELOG and bump version to 6.16.1
  CHANGELOG.asciidoc
  CONTRIBUTING.md
  elasticapm/version.py
Labels: agent-python

#1848 Create and push latest docker image during release
  .github/workflows/release.yml
Labels: agent-python, community, triage

#1847 Pin urllib3==1.26.16 for AWS Lambda compatibility
  .github/dependabot.yml
  CHANGELOG.asciidoc
  dev-utils/requirements.txt
Labels: agent-python

#1850 Add MASK_URL for url sanitization
  elasticapm/conf/constants.py
  elasticapm/utils/__init__.py
  tests/instrumentation/asyncio_tests/httpx_tests.py
  tests/instrumentation/httpx_tests.py
  tests/instrumentation/requests_tests.py
  tests/instrumentation/urllib_tests.py
  tests/utils/tests.py
Labels: agent-python

#1853 update CHANGELOG and bump version to 6.16.2
  CHANGELOG.asciidoc
  elasticapm/version.py
Labels: agent-python

#1854 docs: fix links
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/opentelemetry.asciidoc
Labels: agent-python

#1855 Update api.asciidoc
  docs/api.asciidoc
Labels: agent-python

#1849 [Automation] Update Gherkin specs
  tests/bdd/features/otel_bridge.feature
Labels: automation, agent-python

#1852 implement server_ca_cert_file config option
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  elasticapm/base.py
  elasticapm/conf/__init__.py
  elasticapm/transport/http.py
  elasticapm/transport/http_base.py
  tests/transports/test_urllib3.py
  tests/utils/tests.py
Labels: agent-python

#1863 add pkg-config to test image
  .ci/.matrix_exclude.yml
  tests/Dockerfile
Labels: agent-python
