Repository elastic/apm-agent-python, pull requests merged in 2023-03, with the labels that each got.

#1761 [GRPC] Handle non-existent transaction in server interceptor
  CHANGELOG.asciidoc
  elasticapm/contrib/grpc/server_interceptor.py
  tests/contrib/grpc/grpc_client_tests.py
Labels: agent-python, community, triage

#1765 Fix default botocore handler
  CHANGELOG.asciidoc
  elasticapm/instrumentation/packages/botocore.py
Labels: agent-python

#1767 action: test-docs workflow should create basic junit report
  .github/workflows/test-docs.yml
Labels: bug, automation, agent-python

#1769 Cleanup Jenkins 2 GH Actions Migration
  .ci/jobs/apm-agent-python-mbp.yml
  .ci/jobs/apm-agent-python-nightly-mbp.yml
  .ci/nightly.groovy
  Jenkinsfile
Labels: agent-python, community, triage

#1770 Add a default span name
  CHANGELOG.asciidoc
  elasticapm/traces.py
  tests/instrumentation/base_tests.py
Labels: agent-python

#1775 Lambda support for `event` formed as list
  CHANGELOG.asciidoc
  elasticapm/contrib/serverless/aws.py
  tests/contrib/serverless/aws_tests.py
Labels: agent-python

#1773 Skip flakey windows threading test
  tests/utils/threading_tests.py
Labels: agent-python

#1778 access headers directly
  CHANGELOG.asciidoc
  elasticapm/transport/http.py
  tests/contrib/django/django_tests.py
Labels: agent-python, community, triage

#1774 Migrate specs update to updatecli
  .ci/updatecli.d/update-gherkin-specs.yml
  .ci/updatecli.d/update-json-specs.yml
  .ci/updatecli.d/update-specs.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/updatecli.yml
Labels: agent-python, community, triage

#1781 Handle all non-dict `event` types in lambda
  CHANGELOG.asciidoc
  elasticapm/contrib/serverless/aws.py
Labels: agent-python

#1782 updatecli: fix title since it caused errors
  .ci/updatecli.d/update-gherkin-specs.yml
  .ci/updatecli.d/update-json-specs.yml
  .ci/updatecli.d/update-specs.yml
Labels: agent-python

#1777 Add support for custom transport json_serializer method
  CHANGELOG.asciidoc
  elasticapm/base.py
  elasticapm/conf/__init__.py
Labels: agent-python, community, triage

#1780 Add wrapper instrumentation for Django
  CHANGELOG.asciidoc
  docs/wrapper.asciidoc
  elasticapm/__init__.py
  elasticapm/base.py
  elasticapm/conf/__init__.py
  elasticapm/contrib/django/client.py
  elasticapm/instrumentation/packages/django/__init__.py
  elasticapm/instrumentation/register.py
  elasticapm/instrumentation/wrapper/sitecustomize.py
  tests/contrib/django/wrapper_tests.py
  tests/instrumentation/wrapper/testapp.py
Labels: agent-python

#1785 Fix flakey pylons test
  elasticapm/contrib/pylons/__init__.py
  tests/fixtures.py
Labels: agent-python
