Repository elastic/apm-agent-python, pull requests merged in 2024-02, with the labels that each got.

#1964 Fix test suite
  .ci/.matrix_exclude.yml
Labels: agent-python

#1967 Fix blocking of gRPC stream-to-stream requests when elasticapm is enabled
  elasticapm/contrib/grpc/async_server_interceptor.py
Labels: agent-python, community, triage

#1930 chore: enable dependabot version updates of github-actions yaml files
  .github/dependabot.yml
Labels: automation, agent-python

#1970 contrib/starlette: take into account body reading time
  elasticapm/contrib/starlette/__init__.py
Labels: agent-python, community, triage

#1956 Fix:Update starlette.asciidoc, incorrect middleware order
  docs/starlette.asciidoc
Labels: agent-python, community, triage

#1976 instrumentation: make query scanning for dollar quotes a bit more correct
  elasticapm/instrumentation/packages/dbapi2.py
  tests/instrumentation/dbapi2_tests.py
Labels: agent-python, community, triage

#1977 Cleanup python2 vestiges
  elasticapm/instrumentation/packages/urllib.py
  elasticapm/utils/__init__.py
  tests/client/client_tests.py
  tests/fixtures.py
  tests/instrumentation/urllib_tests.py
  tests/utils/tests.py
Labels: agent-python, community, triage

#1978 ci: re-enable more python 3.12 testing
  .ci/.matrix_exclude.yml
Labels: agent-python, community, triage
