Repository elastic/apm-agent-python, pull requests merged in 2025-04, with the labels that each got.

#2254 Revert "ci: pin actions to specific commits"
  .github/actions/build-distribution/action.yml
  .github/actions/packages/action.yml
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
  .github/workflows/labeler.yml
  .github/workflows/matrix-command.yml
  .github/workflows/microbenchmark.yml
  .github/workflows/packages.yml
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/run-matrix.yml
  .github/workflows/test-docs.yml
  .github/workflows/test-fips.yml
  .github/workflows/test-reporter.yml
  .github/workflows/test.yml
  .github/workflows/updatecli.yml
Labels: agent-python

#2257 github-actions: replace third-party actions
  .github/workflows/labeler.yml
  .github/workflows/pre-commit.yml
Labels: agent-python, community, triage

#2263 github-actions: support gh issues and prs
  .github/workflows/labeler.yml
Labels: community, triage

#2267 tests: bump pytest-localserver to latest
  tests/requirements/reqs-base.txt
Labels: agent-python

#2268 [docs] Update APM, Synthetics, Uptime links
  docs/reference/api-reference.md
  docs/reference/azure-functions-support.md
  docs/reference/configuration.md
  docs/reference/index.md
  docs/reference/lambda-support.md
  docs/reference/opentelemetry-api-bridge.md
Labels: docs, agent-python, Team:Docs

#2270 tests: skip client verify_server_cert disabling tests in fips mode
  tests/client/client_tests.py
Labels: agent-python

#2274 [docs] Fix image paths for docs-assembler
  docs/reference/configuration.md
Labels: docs, agent-python, Team:Docs
