Repository elastic/apm-agent-python, pull requests merged in 2025-08, with the labels that each got.

#2363 feat(tracing): Add span links from SNS messages
  elasticapm/contrib/serverless/aws.py
  tests/contrib/serverless/aws_sns_test_data.json
  tests/contrib/serverless/aws_tests.py
Labels: agent-python, community, triage

#2384 Revert "Drop support for opentracing (#2342)"
  .ci/.matrix_framework.yml
  .ci/.matrix_framework_fips.yml
  .ci/.matrix_framework_full.yml
  elasticapm/contrib/opentracing/__init__.py
  elasticapm/contrib/opentracing/span.py
  elasticapm/contrib/opentracing/tracer.py
  setup.cfg
  tests/contrib/opentracing/__init__.py
  tests/contrib/opentracing/tests.py
  tests/requirements/reqs-opentracing-2.0.txt
  tests/requirements/reqs-opentracing-newest.txt
  tests/scripts/envs/opentracing.sh
Labels: agent-python

#2391 tests: bump MongoDB latest to 4.2
  tests/docker-compose.yml
  tests/scripts/envs/pymongo-newest.sh
Labels: agent-python

#2385 Revert old python support removal
  .ci/.matrix_exclude.yml
  .ci/.matrix_python.yml
  .ci/.matrix_python_full.yml
  .ci/publish-aws.sh
  .github/workflows/test.yml
  Makefile
  docs/reference/run-tests-locally.md
  elasticapm/__init__.py
  elasticapm/base.py
  elasticapm/instrumentation/register.py
  setup.cfg
  tests/client/client_tests.py
  tests/client/exception_tests.py
  tests/client/py3_exception_tests.py
  tests/config/central_config_tests.py
  tests/config/tests.py
  tests/context/test_context.py
  tests/contrib/asyncio/aiohttp_web_tests.py
  tests/contrib/asyncio/starlette_tests.py
  tests/contrib/asyncio/tornado/tornado_tests.py
  tests/contrib/celery/flask_tests.py
  tests/contrib/django/django_tests.py
  tests/contrib/django/wrapper_tests.py
  tests/contrib/flask/flask_tests.py
  tests/contrib/serverless/azurefunctions/azure_functions_tests.py
  tests/events/tests.py
  tests/fixtures.py
  tests/instrumentation/base_tests.py
  tests/instrumentation/transactions_store_tests.py
  tests/instrumentation/urllib_tests.py
  tests/metrics/base_tests.py
  tests/metrics/breakdown_tests.py
  tests/processors/tests.py
  tests/requirements/lint-isort.txt
  tests/requirements/reqs-base.txt
  tests/scripts/envs/azure.sh
  tests/scripts/run_tests.sh
  tests/transports/test_base.py
  tests/transports/test_urllib3.py
  tests/utils/cloud_tests.py
  tests/utils/compat_tests.py
  tests/utils/stacks/tests.py
  tests/utils/threading_tests.py
Labels: agent-python

#2396 docs: Fix typo in PR number for 6.24.0 changelog
  CHANGELOG.asciidoc
  docs/release-notes/index.md
Labels: agent-python

#2397 Add flag to skip build-distrubution execution step when release
  .github/workflows/release.yml
  .github/workflows/test-release.yml
  .github/workflows/test.yml
Labels: bug, agent-python
